spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sopt_32?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: sopt_server
    password: Qwer1234!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: youcantreavelthesecretkey1234012300040

cloud:
  aws:
    credentials:
      accessKey: AKIASEBYH7CLU4PJKM66
      secretKey: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: sopt32-seminar-hong
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

springdoc:
  packages-to-scan: sopt.org.fourthSeminar
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpah
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache: